<?php
require_once __DIR__.'/../../config/bootstrap.php'; require_internal();
$pdo=db(); $pageTitle='Financeiro'; $tab=$_GET['tab']??'mov';
$pdo->exec("UPDATE parcelas SET status='Vencido' WHERE tipo='Pagar' AND status='Pendente' AND date(vencimento)<date('now')");
$pdo->exec("UPDATE movimentacoes_financeiras SET status='Vencido' WHERE status='Pendente' AND vencimento IS NOT NULL AND date(vencimento)<date('now')");
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf(); $action=$_POST['action']??'';
 if($action==='new'){
  $type=$_POST['tipo'];$desc=trim($_POST['descricao']);$cat=trim($_POST['categoria']);$v=number_value($_POST['valor']);$due=$_POST['vencimento']?:null;$status=$_POST['status']??'Pendente';
  if($desc!==''&&$v>0){$pay=$status==='Pago'?today():null;$pdo->prepare('INSERT INTO movimentacoes_financeiras(tipo,categoria,descricao,valor,vencimento,data_pagamento,status,usuario_id,origem,referencia_id,observacao,criado_em) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$type,$cat,$desc,$v,$due,$pay,$status,current_user()['id'],'manual',null,trim($_POST['observacao']??''),now()]);log_action('lançamento financeiro');flash('success','Lançamento criado.');redirect('index.php');}
 }
 if($action==='pay'){$id=(int)$_POST['id'];$pdo->prepare("UPDATE movimentacoes_financeiras SET status='Pago',data_pagamento=? WHERE id=?")->execute([today(),$id]);log_action('pagamento financeiro','movimentacoes_financeiras',$id);flash('success','Lançamento marcado como pago.');redirect('index.php');}
 if($action==='pay_installment'){$id=(int)$_POST['id'];$pdo->prepare("UPDATE parcelas SET status='Pago',pagamento=? WHERE id=?")->execute([today(),$id]);$pdo->prepare("UPDATE movimentacoes_financeiras SET status='Pago',data_pagamento=? WHERE origem='compra_parcela' AND referencia_id=?")->execute([today(),$id]);log_action('pagamento','parcelas',$id);flash('success','Parcela paga.');redirect('index.php?tab=payable');}
}
$payable=$pdo->query("SELECT p.*,f.nome fornecedor FROM parcelas p LEFT JOIN fornecedores f ON f.id=p.fornecedor_id WHERE p.tipo='Pagar' ORDER BY p.status DESC,p.vencimento")->fetchAll();
$receivable=$pdo->query("SELECT m.*,c.nome cliente FROM movimentacoes_financeiras m LEFT JOIN vendas v ON v.id=m.referencia_id AND m.origem='venda' LEFT JOIN clientes c ON c.id=v.cliente_id WHERE m.tipo='Entrada' AND m.status IN ('Pendente','Vencido') ORDER BY m.vencimento,m.id")->fetchAll();
$all=$pdo->query('SELECT m.*,u.nome usuario_nome FROM movimentacoes_financeiras m JOIN usuarios u ON u.id=m.usuario_id ORDER BY m.id DESC LIMIT 300')->fetchAll();
include __DIR__.'/../../includes/header.php'; ?>
<div class="page-head"><h1>Financeiro</h1></div><div class="tabs"><a class="tab <?=$tab==='mov'?'active':''?>" href="?tab=mov">Movimentações</a><a class="tab <?=$tab==='payable'?'active':''?>" href="?tab=payable">Contas a Pagar</a><a class="tab <?=$tab==='receivable'?'active':''?>" href="?tab=receivable">Contas a Receber</a></div>
<?php if($tab==='mov'): ?><div class="grid grid-3"><div class="card" style="grid-column:span 2"><h3>Novo lançamento</h3><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="new"><div class="form-grid"><div class="field col-3"><label>Tipo</label><select name="tipo"><option>Entrada</option><option>Saída</option></select></div><div class="field col-3"><label>Categoria</label><input name="categoria"></div><div class="field col-6"><label>Descrição</label><input name="descricao" required></div><div class="field col-4"><label>Valor</label><input type="number" step="0.01" min="0.01" name="valor" required></div><div class="field col-4"><label>Vencimento</label><input type="date" name="vencimento"></div><div class="field col-4"><label>Status</label><select name="status"><option>Pendente</option><option>Pago</option></select></div><div class="field col-12"><label>Observação</label><input name="observacao"></div></div><button class="btn primary">Lançar</button></form></div><div class="card"><h3>Resumo</h3><?php $ent=(float)$pdo->query("SELECT COALESCE(SUM(valor),0) FROM movimentacoes_financeiras WHERE tipo='Entrada' AND status='Pago'")->fetchColumn();$sai=(float)$pdo->query("SELECT COALESCE(SUM(valor),0) FROM movimentacoes_financeiras WHERE tipo='Saída' AND status='Pago'")->fetchColumn(); ?><div class="total-line"><span>Entradas pagas</span><strong><?=money($ent)?></strong></div><div class="total-line"><span>Saídas pagas</span><strong><?=money($sai)?></strong></div><div class="total-line total"><span>Saldo</span><strong><?=money($ent-$sai)?></strong></div></div></div><div class="card" style="margin-top:16px"><h3>Lançamentos</h3><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Tipo</th><th>Categoria</th><th>Descrição</th><th>Valor</th><th>Vencimento</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($all as $m): ?><tr><td><?=datetime_br($m['criado_em'])?></td><td><?=e($m['tipo'])?></td><td><?=e($m['categoria'])?></td><td><?=e($m['descricao'])?></td><td><?=money($m['valor'])?></td><td><?=date_br($m['vencimento'])?></td><td><?=status_badge($m['status'])?></td><td><?php if($m['status']!=='Pago'&&$m['status']!=='Cancelado'): ?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="pay"><input type="hidden" name="id" value="<?=$m['id']?>"><button class="btn small secondary">Baixar</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php elseif($tab==='payable'): ?><div class="card"><h3>Contas a pagar</h3><div class="table-wrap"><table class="table"><thead><tr><th>Fornecedor</th><th>Compra</th><th>Parcela</th><th>Valor</th><th>Vencimento</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($payable as $p): ?><tr><td><?=e($p['fornecedor'])?></td><td>#<?=e($p['compra_id'])?></td><td><?=e($p['numero_parcela'])?>/<?=e($p['quantidade_parcelas'])?></td><td><?=money($p['valor'])?></td><td><?=date_br($p['vencimento'])?></td><td><?=status_badge($p['status'])?></td><td><?php if($p['status']!=='Pago'&&$p['status']!=='Cancelado'): ?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="pay_installment"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="btn small primary">Pagar</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><p class="muted">O pagamento das parcelas de compras ocorre pelo cadastro da compra/rotina financeira correspondente.</p></div>
<?php else: ?><div class="card"><h3>Contas a receber</h3><div class="table-wrap"><table class="table"><thead><tr><th>Vencimento</th><th>Origem</th><th>Cliente</th><th>Descrição</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($receivable as $m): ?><tr><td><?=date_br($m['vencimento'])?></td><td><?=e($m['origem'])?></td><td><?=e($m['cliente']?:'—')?></td><td><?=e($m['descricao'])?></td><td><?=money($m['valor'])?></td><td><?=status_badge($m['status'])?></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="pay"><input type="hidden" name="id" value="<?=$m['id']?>"><button class="btn small primary">Baixar</button></form></td></tr><?php endforeach;if(!$receivable): ?><tr><td colspan="7" class="empty">Nenhum recebível pendente.</td></tr><?php endif;?></tbody></table></div></div><?php endif; ?><?php include __DIR__.'/../../includes/footer.php'; ?>
