<?php require_once __DIR__.'/../config/bootstrap.php'; require_internal(); require_first_access_clear(); $pageTitle='Início';
$pdo=db(); $today=today();
$sales=$pdo->prepare("SELECT COUNT(*) qtd, COALESCE(SUM(total),0) total FROM vendas WHERE status='Concluida' AND date(data_venda)=?");$sales->execute([$today]);$sales=$sales->fetch();
$orders=(int)$pdo->query("SELECT COUNT(*) FROM encomendas WHERE status IN ('Aberta','Aguardando','Confirmada','Em preparação','Pronta')")->fetchColumn();
$low=(int)$pdo->query("SELECT COUNT(*) FROM produtos WHERE ativo=1 AND estoque<=estoque_minimo")->fetchColumn();
$overdue=(int)$pdo->query("SELECT COUNT(*) FROM parcelas WHERE status IN ('Pendente','Vencido') AND date(vencimento)<date('now') AND tipo='Pagar'")->fetchColumn();
$cash=open_cash();
$entry=(float)$pdo->query("SELECT COALESCE(SUM(valor),0) FROM movimentacoes_financeiras WHERE tipo='Entrada' AND date(COALESCE(data_pagamento,criado_em))='$today'")->fetchColumn();
$out=(float)$pdo->query("SELECT COALESCE(SUM(valor),0) FROM movimentacoes_financeiras WHERE tipo='Saída' AND date(COALESCE(data_pagamento,criado_em))='$today'")->fetchColumn();
include __DIR__.'/../includes/header.php'; ?>
<div class="page-head"><div><h1>Visão geral</h1><div class="muted">Operação integrada da livraria.</div></div><div class="actions"><a class="btn primary" href="<?=e(app_url('/admin/pdv/index.php'))?>">＋ Nova venda</a><a class="btn secondary" href="<?=e(app_url('/admin/encomendas/form.php'))?>">＋ Nova encomenda</a></div></div>
<div class="dashboard-grid"><div class="card stat kpi-accent"><span class="label">Vendas hoje</span><span class="value"><?=money($sales['total'])?></span><span class="muted"><?=$sales['qtd']?> venda(s)</span></div><div class="card stat"><span class="label">Encomendas pendentes</span><span class="value"><?=$orders?></span><span class="muted">Acompanhamento operacional</span></div><div class="card stat"><span class="label">Estoque baixo</span><span class="value"><?=$low?></span><span class="muted">Produtos no mínimo ou abaixo</span></div><div class="card stat"><span class="label">Contas vencidas</span><span class="value"><?=$overdue?></span><span class="muted">Contas a pagar</span></div></div>
<div class="grid grid-3" style="margin-top:16px"><div class="card"><h3>Caixa</h3><?php if($cash): ?><p><strong>Aberto</strong> desde <?=datetime_br($cash['abertura_em'])?></p><p>Valor inicial: <?=money($cash['valor_inicial'])?></p><a class="btn secondary" href="<?=e(app_url('/admin/caixa/index.php'))?>">Abrir módulo</a><?php else: ?><p class="muted">Nenhum caixa aberto.</p><a class="btn primary" href="<?=e(app_url('/admin/caixa/index.php'))?>">Abrir caixa</a><?php endif; ?></div><div class="card"><h3>Fluxo financeiro hoje</h3><div class="total-line"><span>Entradas</span><strong><?=money($entry)?></strong></div><div class="total-line"><span>Saídas</span><strong><?=money($out)?></strong></div><div class="total-line total"><span>Saldo</span><strong><?=money($entry-$out)?></strong></div></div><div class="card"><h3>Atalhos</h3><div class="actions"><a class="btn secondary" href="<?=e(app_url('/admin/produtos/form.php'))?>">Novo produto</a><a class="btn secondary" href="<?=e(app_url('/admin/estoque/index.php'))?>">Entrada de estoque</a><a class="btn secondary" href="<?=e(app_url('/admin/compras/form.php'))?>">Nova compra</a><a class="btn secondary" href="<?=e(app_url('/admin/relatorios/index.php'))?>">Relatórios</a></div></div></div>
<div class="card" style="margin-top:16px"><h3>Itens de estoque baixo</h3><div class="table-wrap"><table class="table"><thead><tr><th>Produto</th><th>Estoque</th><th>Mínimo</th><th>Situação</th></tr></thead><tbody><?php $rows=$pdo->query("SELECT nome,estoque,estoque_minimo FROM produtos WHERE ativo=1 AND estoque<=estoque_minimo ORDER BY estoque,nome LIMIT 10")->fetchAll(); if(!$rows): ?><tr><td colspan="4" class="empty">Nenhum alerta de estoque.</td></tr><?php else: foreach($rows as $r): ?><tr><td><?=e($r['nome'])?></td><td><?=e($r['estoque'])?></td><td><?=e($r['estoque_minimo'])?></td><td><?=status_badge('Estoque baixo')?></td></tr><?php endforeach; endif;?></tbody></table></div></div>
<?php include __DIR__.'/../includes/footer.php'; ?>
